# Generated by Django 4.1.3 on 2022-11-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=2048)),
                ('post_content', models.TextField()),
                ('publish_date', models.DateField()),
                ('author_name', models.CharField(max_length=512)),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
