# Generated by Django 4.1.3 on 2022-11-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
    ]
