# Generated by Django 4.1.3 on 2022-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
