# Generated by Django 4.1.3 on 2022-11-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppORM', '0002_alter_post_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=1024),
        ),
    ]
