# Generated by Django 4.1.3 on 2022-11-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Content',
            new_name='content',
        ),
    ]
